#!/usr/bin/env python3
"""One-off — country centroids for the daily challenge's distance feedback.

Fetches Natural Earth 10m admin-0 label points (public domain), maps them onto the
schema registry's ISO alpha-2 keys, and emits packages/schema/src/centroids.ts.
The raw GeoJSON is cached under data/cache/centroids/ so re-runs are offline.
Fails loudly when any registry country lacks a centroid.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CACHE = ROOT / 'data/cache/centroids'
OUT = ROOT / 'packages/schema/src/centroids.ts'

GEOJSON_URL = (
    'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/'
    'master/geojson/ne_10m_admin_0_countries.geojson'
)

UA = {
    'User-Agent': (
        'soup-quiz-dataset-pipeline/0.1 '
        '(https://github.com/stilkin/soup-quiz; dev contact via repo)'
    )
}

# ISO alpha-2 property candidates, tried in order — NE marks some countries '-99'
# in ADM0_A2 (notably FR/NO); ISO_A2_EH is the least quirky in current versions.
ISO_FIELDS = ('ISO_A2_EH', 'ADM0_A2', 'SOV_A2')

# Registry codes that Natural Earth keys differently; grow only after a fail-loud run.
ISO_PATCH: dict[str, str] = {}

# Registry territories NE folds into sovereign features (French overseas, Pacific
# islands, Svalbard…). Approximate label points, committed here so regeneration is
# reproducible; none can be a soup's country — they only serve as guesses.
EXTRA_CENTROIDS: dict[str, tuple[float, float]] = {
    'BQ': (12.15, -68.28),   # Caribbean Netherlands (Bonaire)
    'BV': (-54.42, 3.35),    # Bouvet Island
    'CC': (-12.16, 96.91),   # Cocos (Keeling) Islands
    'CX': (-10.42, 105.68),  # Christmas Island
    'GF': (4.0, -53.0),      # French Guiana
    'GP': (16.24, -61.53),   # Guadeloupe
    'MQ': (14.64, -61.02),   # Martinique
    'RE': (-21.12, 55.54),   # Réunion
    'SJ': (78.0, 16.0),      # Svalbard and Jan Mayen
    'TK': (-9.2, -171.8),    # Tokelau
    'YT': (-12.83, 45.17),   # Mayotte
}


def registry_keys() -> list[str]:
    src = (ROOT / 'packages/schema/src/registries.ts').read_text(encoding='utf-8')
    block = re.search(r'export const COUNTRIES[^=]*= \{(.*?)\n\}', src, re.S).group(1)
    return re.findall(r'^\s{2}([A-Z]{2}): ', block, re.M)


def main() -> int:
    CACHE.mkdir(parents=True, exist_ok=True)
    raw = CACHE / 'ne_10m_admin_0_countries.geojson'
    if not raw.exists():
        request = urllib.request.Request(GEOJSON_URL, headers=UA)
        with urllib.request.urlopen(request, timeout=600) as response, open(raw, 'wb') as f:
            f.write(response.read())
        print(f'fetched {raw.stat().st_size / 1e6:.1f} MB (cached for offline re-runs)')

    data = json.loads(raw.read_text(encoding='utf-8'))
    coords: dict[str, tuple[float, float]] = {}
    skipped = set()
    for feature in data['features']:
        props = feature['properties']
        code = next(
            (props[field] for field in ISO_FIELDS
             if re.fullmatch(r'[A-Z]{2}', str(props.get(field) or ''))),
            None,
        )
        if code is None:
            skipped.add(str(props.get('NAME')) or '?')
            continue
        code = ISO_PATCH.get(code, code)
        lon, lat = props.get('LABEL_X'), props.get('LABEL_Y')
        if lon is None or lat is None:
            continue
        # 2 decimals ≈ 1 km — plenty for heat banding
        coords.setdefault(code, (round(lat, 2), round(lon, 2)))

    for code, (lat, lon) in EXTRA_CENTROIDS.items():
        coords.setdefault(code, (lat, lon))

    keys = set(registry_keys())
    missing = sorted(keys - coords.keys())
    if missing:
        print(f'MISSING centroids for {len(missing)} registry countries: {missing}')
        print('grow ISO_PATCH or widen ISO_FIELDS, then re-run')
        return 1
    unused = sorted(coords.keys() - keys)
    if unused:
        print(f'ignoring {len(unused)} non-registry codes: {unused}')
    if skipped:
        print(f'features without a usable ISO code (ignored): {sorted(skipped)[:6]} …')

    entries = ',\n'.join(
        f'  {code}: {{ lat: {lat}, lon: {lon} }}'
        for code, (lat, lon) in sorted(coords.items()) if code in keys
    )
    OUT.write_text(
        '// GENERATED by data/pipeline/07_centroids.py — do not edit by hand.\n'
        '// Source: Natural Earth 10m admin-0 label points (public domain).\n'
        '// Re-run the script to regenerate; coverage is enforced by tests.\n'
        '\n'
        'export interface Centroid {\n'
        '  lat: number\n'
        '  lon: number\n'
        '}\n'
        '\n'
        'export const CENTROIDS: Readonly<Record<string, Centroid>> = {\n'
        f'{entries},\n'
        '}\n',
        encoding='utf-8',
    )
    print(f'wrote {OUT.name}: {len(keys)} centroids')
    return 0


if __name__ == '__main__':
    sys.exit(main())
